# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serialportform.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialPortWindow(object):
    def setupUi(self, SerialPortWindow):
        SerialPortWindow.setObjectName("SerialPortWindow")
        SerialPortWindow.resize(821, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SerialPortWindow.sizePolicy().hasHeightForWidth())
        SerialPortWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SerialPortWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBoxPort = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxPort.setGeometry(QtCore.QRect(90, 30, 121, 31))
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBoxBaud = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBaud.setGeometry(QtCore.QRect(90, 80, 121, 31))
        self.comboBoxBaud.setObjectName("comboBoxBaud")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.comboBoxCheckSum = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxCheckSum.setGeometry(QtCore.QRect(90, 130, 121, 31))
        self.comboBoxCheckSum.setObjectName("comboBoxCheckSum")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.comboBoxBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBits.setGeometry(QtCore.QRect(90, 180, 121, 31))
        self.comboBoxBits.setObjectName("comboBoxBits")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBoxStopBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxStopBits.setGeometry(QtCore.QRect(90, 230, 121, 31))
        self.comboBoxStopBits.setObjectName("comboBoxStopBits")
        self.pushButtonOpenSerial = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonOpenSerial.setGeometry(QtCore.QRect(10, 280, 201, 31))
        self.pushButtonOpenSerial.setObjectName("pushButtonOpenSerial")
        self.textEditReceived = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditReceived.setGeometry(QtCore.QRect(260, 50, 551, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditReceived.sizePolicy().hasHeightForWidth())
        self.textEditReceived.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditReceived.setFont(font)
        self.textEditReceived.setReadOnly(True)
        self.textEditReceived.setObjectName("textEditReceived")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 350, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBoxSaveAsFile = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxSaveAsFile.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.checkBoxSaveAsFile.setObjectName("checkBoxSaveAsFile")
        self.checkBoxNewLine = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxNewLine.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.checkBoxNewLine.setObjectName("checkBoxNewLine")
        self.checkBoxDisplayHex = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxDisplayHex.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.checkBoxDisplayHex.setObjectName("checkBoxDisplayHex")
        self.checkBoxStopReceive = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxStopReceive.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.checkBoxStopReceive.setObjectName("checkBoxStopReceive")
        self.pushButtonOpenRecvFile = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonOpenRecvFile.setGeometry(QtCore.QRect(130, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonOpenRecvFile.setFont(font)
        self.pushButtonOpenRecvFile.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonOpenRecvFile.setFlat(True)
        self.pushButtonOpenRecvFile.setObjectName("pushButtonOpenRecvFile")
        self.pushButtonClearRecvArea = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonClearRecvArea.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.pushButtonClearRecvArea.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonClearRecvArea.setFlat(True)
        self.pushButtonClearRecvArea.setObjectName("pushButtonClearRecvArea")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 490, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBoxSendFile = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSendFile.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.checkBoxSendFile.setObjectName("checkBoxSendFile")
        self.checkBoxEmptyAfterSent = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxEmptyAfterSent.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.checkBoxEmptyAfterSent.setObjectName("checkBoxEmptyAfterSent")
        self.checkBoxSendHex = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSendHex.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.checkBoxSendHex.setObjectName("checkBoxSendHex")
        self.checkBoxSendLooping = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSendLooping.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.checkBoxSendLooping.setObjectName("checkBoxSendLooping")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(121, 80, 41, 22))
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(160, 80, 46, 21))
        self.label_6.setObjectName("label_6")
        self.pushButtonOpenSendFile = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonOpenSendFile.setGeometry(QtCore.QRect(120, 20, 75, 23))
        self.pushButtonOpenSendFile.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonOpenSendFile.setFlat(True)
        self.pushButtonOpenSendFile.setObjectName("pushButtonOpenSendFile")
        self.pushButtonClearSendArea = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonClearSendArea.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.pushButtonClearSendArea.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonClearSendArea.setFlat(True)
        self.pushButtonClearSendArea.setObjectName("pushButtonClearSendArea")
        self.textEditSent = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSent.setGeometry(QtCore.QRect(260, 330, 481, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditSent.setFont(font)
        self.textEditSent.setObjectName("textEditSent")
        self.pushButtonSendData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSendData.setGeometry(QtCore.QRect(750, 330, 61, 221))
        self.pushButtonSendData.setObjectName("pushButtonSendData")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 20, 551, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxCD = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxCD.setFont(font)
        self.checkBoxCD.setObjectName("checkBoxCD")
        self.horizontalLayout.addWidget(self.checkBoxCD)
        self.checkBoxRXD = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRXD.setFont(font)
        self.checkBoxRXD.setObjectName("checkBoxRXD")
        self.horizontalLayout.addWidget(self.checkBoxRXD)
        self.checkBoxTXD = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxTXD.setFont(font)
        self.checkBoxTXD.setObjectName("checkBoxTXD")
        self.horizontalLayout.addWidget(self.checkBoxTXD)
        self.checkBoxDTR = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxDTR.setFont(font)
        self.checkBoxDTR.setObjectName("checkBoxDTR")
        self.horizontalLayout.addWidget(self.checkBoxDTR)
        self.checkBoxGND = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxGND.setFont(font)
        self.checkBoxGND.setObjectName("checkBoxGND")
        self.horizontalLayout.addWidget(self.checkBoxGND)
        self.checkBoxDSR = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxDSR.setFont(font)
        self.checkBoxDSR.setObjectName("checkBoxDSR")
        self.horizontalLayout.addWidget(self.checkBoxDSR)
        self.checkBoxRTS = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRTS.setFont(font)
        self.checkBoxRTS.setObjectName("checkBoxRTS")
        self.horizontalLayout.addWidget(self.checkBoxRTS)
        self.checkBoxCTS = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxCTS.setFont(font)
        self.checkBoxCTS.setObjectName("checkBoxCTS")
        self.horizontalLayout.addWidget(self.checkBoxCTS)
        self.checkBoxRI = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRI.setFont(font)
        self.checkBoxRI.setObjectName("checkBoxRI")
        self.horizontalLayout.addWidget(self.checkBoxRI)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 570, 548, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonClearAllCounts = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonClearAllCounts.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonClearAllCounts.setFlat(True)
        self.pushButtonClearAllCounts.setObjectName("pushButtonClearAllCounts")
        self.horizontalLayout_2.addWidget(self.pushButtonClearAllCounts)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEditReceivedCounts = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditReceivedCounts.setReadOnly(True)
        self.lineEditReceivedCounts.setObjectName("lineEditReceivedCounts")
        self.horizontalLayout_2.addWidget(self.lineEditReceivedCounts)
        self.pushButtonClearRecvCounts = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonClearRecvCounts.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonClearRecvCounts.setFlat(True)
        self.pushButtonClearRecvCounts.setObjectName("pushButtonClearRecvCounts")
        self.horizontalLayout_2.addWidget(self.pushButtonClearRecvCounts)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.lineEditSentCounts = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditSentCounts.setReadOnly(True)
        self.lineEditSentCounts.setObjectName("lineEditSentCounts")
        self.horizontalLayout_2.addWidget(self.lineEditSentCounts)
        self.pushButtonClearSentCounts = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonClearSentCounts.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color:blue;")
        self.pushButtonClearSentCounts.setFlat(True)
        self.pushButtonClearSentCounts.setObjectName("pushButtonClearSentCounts")
        self.horizontalLayout_2.addWidget(self.pushButtonClearSentCounts)
        SerialPortWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SerialPortWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 21))
        self.menubar.setObjectName("menubar")
        SerialPortWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SerialPortWindow)
        self.statusbar.setObjectName("statusbar")
        SerialPortWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SerialPortWindow)
        QtCore.QMetaObject.connectSlotsByName(SerialPortWindow)

    def retranslateUi(self, SerialPortWindow):
        _translate = QtCore.QCoreApplication.translate
        SerialPortWindow.setWindowTitle(_translate("SerialPortWindow", "串口调试助手"))
        self.groupBox.setTitle(_translate("SerialPortWindow", "端口设置"))
        self.label_2.setText(_translate("SerialPortWindow", "端口:"))
        self.label.setText(_translate("SerialPortWindow", "波特率:"))
        self.label_3.setText(_translate("SerialPortWindow", "校验位:"))
        self.label_4.setText(_translate("SerialPortWindow", "数据位:"))
        self.label_5.setText(_translate("SerialPortWindow", "停止位:"))
        self.pushButtonOpenSerial.setText(_translate("SerialPortWindow", "打开"))
        self.groupBox_2.setTitle(_translate("SerialPortWindow", "接收区设置"))
        self.checkBoxSaveAsFile.setText(_translate("SerialPortWindow", "另存为文件"))
        self.checkBoxNewLine.setText(_translate("SerialPortWindow", "自动换行显示"))
        self.checkBoxDisplayHex.setText(_translate("SerialPortWindow", "十六进制显示"))
        self.checkBoxStopReceive.setText(_translate("SerialPortWindow", "暂停接收显示"))
        self.pushButtonOpenRecvFile.setText(_translate("SerialPortWindow", "打开文件"))
        self.pushButtonClearRecvArea.setText(_translate("SerialPortWindow", "清空接收区"))
        self.groupBox_3.setTitle(_translate("SerialPortWindow", "发送区设置"))
        self.checkBoxSendFile.setText(_translate("SerialPortWindow", "发送文件"))
        self.checkBoxEmptyAfterSent.setText(_translate("SerialPortWindow", "发送完清空"))
        self.checkBoxSendHex.setText(_translate("SerialPortWindow", "十六进制输入"))
        self.checkBoxSendLooping.setText(_translate("SerialPortWindow", "自动循环"))
        self.label_6.setText(_translate("SerialPortWindow", "*100ms"))
        self.pushButtonOpenSendFile.setText(_translate("SerialPortWindow", "打开文件"))
        self.pushButtonClearSendArea.setText(_translate("SerialPortWindow", "清空发送区"))
        self.pushButtonSendData.setText(_translate("SerialPortWindow", "发送"))
        self.checkBoxCD.setText(_translate("SerialPortWindow", "1.CD"))
        self.checkBoxRXD.setText(_translate("SerialPortWindow", "2.RXD"))
        self.checkBoxTXD.setText(_translate("SerialPortWindow", "3.TXD"))
        self.checkBoxDTR.setText(_translate("SerialPortWindow", "4.DTR"))
        self.checkBoxGND.setText(_translate("SerialPortWindow", "5.GND"))
        self.checkBoxDSR.setText(_translate("SerialPortWindow", "6.DSR"))
        self.checkBoxRTS.setText(_translate("SerialPortWindow", "7.RTS"))
        self.checkBoxCTS.setText(_translate("SerialPortWindow", "8.CTS"))
        self.checkBoxRI.setText(_translate("SerialPortWindow", "9.RI"))
        self.pushButtonClearAllCounts.setText(_translate("SerialPortWindow", "全部计数复位"))
        self.label_7.setText(_translate("SerialPortWindow", "接收:"))
        self.pushButtonClearRecvCounts.setText(_translate("SerialPortWindow", "接收计数复位"))
        self.label_8.setText(_translate("SerialPortWindow", "发送:"))
        self.pushButtonClearSentCounts.setText(_translate("SerialPortWindow", "发送计数复位"))

